version: "3"

services:
  app:
    build: .
    command: npm start
    container_name: portaldecursosonlinefc-docker
    ports:
      - 3000:3000
    volumes:
      - /usr/app
      - /usr/appnode_modules
